# Generated by Django 4.2.7 on 2026-03-12 20:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Intern title/role', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('extended', 'Extended'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=20)),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly stipend amount', max_digits=10, null=True)),
                ('working_hours_per_week', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='placements/offer_letters/')),
                ('contract', models.FileField(blank=True, null=True, upload_to='placements/contracts/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='placements.department')),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'intern'}, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL)),
                ('supervisors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'supervisor'}, related_name='supervised_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rotation_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rotations', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotations_from', to='placements.department')),
                ('intern', models.ForeignKey(limit_choices_to={'role': 'intern'}, on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotations_to', to='placements.department')),
            ],
            options={
                'ordering': ['-rotation_date'],
                'indexes': [models.Index(fields=['intern', 'rotation_date'], name='placements__intern__0ec6ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='placements.placement')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['placement', '-changed_at'], name='placements__placeme_fe603a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['intern', 'status'], name='placements__intern__d8ffa3_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['department', 'status'], name='placements__departm_c92cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['start_date', 'end_date'], name='placements__start_d_a02140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placement',
            unique_together={('intern', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='placements__code_ac1bce_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='placements__is_acti_7e25dd_idx'),
        ),
    ]
