# Generated by Django 6.0.3 on 2026-04-11 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, help_text='Hours worked', max_digits=5, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs_revision')], db_index=True, default='draft', max_length=30)),
                ('category', models.CharField(choices=[('development', 'Development'), ('research', 'Research'), ('admin', 'Admin'), ('other', 'Other')], db_index=True, default='development', help_text='Category', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
