# Generated by Django 6.0.3 on 2026-04-10 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('BUG', 'Technical Bug'), ('DATA', 'Data Discrepancy'), ('ACCESS', 'Permission Issue'), ('OTHER', 'Other')], default='BUG', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='internshipplacement',
            name='unique_placement_per_start_date',
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='internshipplacement',
            constraint=models.UniqueConstraint(fields=('student', 'start_date'), name='unique_placement_date'),
        ),
        migrations.AddConstraint(
            model_name='weeklylog',
            constraint=models.UniqueConstraint(fields=('placement', 'week_number'), name='unique_week_per_placement'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
